/// The two markdown deliverables, rendered from the audit's own data.
///
/// Every table is generated; the prose lives in `report_prose.dart`. A report
/// typed by hand would be a copy of the numbers that can disagree with them, and
/// the disagreement would be invisible — which is the failure this audit exists
/// to find in the palette.
library;

import 'report_prose.dart';

String cell(Object? value) => (value?.toString() ?? '').replaceAll('|', r'\|');

/// `design_audit/color_system_report.md`.
String buildReportMarkdown({
  required Map<String, Object?> inventory,
  required Map<String, Object?> violations,
  required Map<String, Object?> perceptual,
  required Map<String, Object?> roles,
}) {
  final rows = (violations['violations']! as List<Object?>)
      .cast<Map<String, Object?>>();

  String cell(Object? value) =>
      (value?.toString() ?? '').replaceAll('|', r'\|');

  // ---------------------------------------------------------------- report
  final report = StringBuffer()
    ..writeln('# Colour system conformance audit')
    ..writeln()
    ..writeln(
      'Generated by `test/design_audit/audit_test.dart` from the audit data. '
      'this directory. Re-run with '
      '`flutter test test/design_audit/`.',
    )
    ..writeln()
    ..writeln(scopeNote)
    ..writeln()
    ..writeln('## 1. Summary')
    ..writeln()
    ..writeln('| | |')
    ..writeln('|---|---|')
    ..writeln(
      '| Files scanned (`lib/`, hand-written) | ${inventory['scannedFiles']} |',
    )
    ..writeln('| Colour sites found | ${inventory['totalSites']} |')
    ..writeln('| Violations | ${violations['totalViolations']} |')
    ..writeln()
    ..writeln('**By element kind**')
    ..writeln()
    ..writeln('| kind | sites |')
    ..writeln('|---|---|');
  (inventory['byElementKind']! as Map<String, Object?>).forEach((k, v) {
    report.writeln('| $k | $v |');
  });
  report
    ..writeln()
    ..writeln('**By source kind**')
    ..writeln()
    ..writeln('| kind | sites |')
    ..writeln('|---|---|');
  (inventory['bySourceKind']! as Map<String, Object?>).forEach((k, v) {
    report.writeln('| $k | $v |');
  });
  report
    ..writeln()
    ..writeln('**By violation code**')
    ..writeln()
    ..writeln('| code | count | meaning |')
    ..writeln('|---|---|---|');
  (violations['byCode']! as Map<String, Object?>).forEach((k, v) {
    report.writeln('| $k | $v | ${codeMeanings[k]} |');
  });

  report
    ..writeln()
    ..writeln('## 2. Violations')
    ..writeln()
    ..writeln(
      '| code | sev | file:line | context | current (light) | current (dark) | proposed target |',
    )
    ..writeln('|---|---|---|---|---|---|---|');
  for (final row in rows) {
    final location = row['line'] == 0
        ? cell(row['file'])
        : '${cell(row['file'])}:${row['line']}';
    report.writeln(
      '| ${row['code']} | ${row['severity']} | `$location` '
      '| ${cell(row['expression'])} '
      '| `${cell(row['resolved_value_light'])}` '
      '| `${cell(row['resolved_value_dark'])}` '
      '| ${cell(row['proposed_target_token'])} |',
    );
  }
  for (final row in rows) {
    report.writeln();
    report.writeln(
      '- **${row['code']}** `${cell(row['expression'])}` — ${cell(row['why'])}',
    );
  }

  // ------------------------------------------------------ perceptual answers
  report
    ..writeln()
    ..writeln('## 3. Perceptual checks')
    ..writeln()
    ..writeln(perceptualPreamble)
    ..writeln()
    ..writeln('### Border prominence')
    ..writeln()
    ..writeln('| mode | border on ground | ratio | verdict |')
    ..writeln('|---|---|---|---|');
  for (final mode in <String>['light', 'dark']) {
    final block =
        (perceptual[mode]! as Map<String, Object?>)['borderProminence']!
            as Map<String, Object?>;
    block.forEach((k, v) {
      final entry = v! as Map<String, Object?>;
      final ratio = (entry['ratio']! as num).toStringAsFixed(2);
      report.writeln('| $mode | $k | $ratio | ${entry['verdict']} |');
    });
  }

  report
    ..writeln()
    ..writeln('### Background tint')
    ..writeln()
    ..writeln('| mode | surface | hex | hue | saturation | pure neutral |')
    ..writeln('|---|---|---|---|---|---|');
  for (final mode in <String>['light', 'dark']) {
    final tint =
        (perceptual[mode]! as Map<String, Object?>)['backgroundTint']!
            as Map<String, Object?>;
    tint.forEach((which, v) {
      final entry = v! as Map<String, Object?>;
      final hue = entry['hue'] == null
          ? 'none'
          : (entry['hue']! as num).round().toString();
      report.writeln(
        '| $mode | $which | `${entry['hex']}` | $hue '
        '| ${(entry['saturation']! as num).toStringAsFixed(3)} '
        '| ${entry['isPureNeutral']} |',
      );
    });
  }

  report
    ..writeln()
    ..writeln('### Neutral family coherence')
    ..writeln()
    ..writeln('| mode | token | hex | hue |')
    ..writeln('|---|---|---|---|');
  for (final mode in <String>['light', 'dark']) {
    final family =
        (perceptual[mode]! as Map<String, Object?>)['neutralFamilyCoherence']!
            as Map<String, Object?>;
    family.forEach((which, v) {
      final entry = v! as Map<String, Object?>;
      final hue = entry['hue'] == null
          ? '**none**'
          : (entry['hue']! as num).round().toString();
      report.writeln('| $mode | $which | `${entry['hex']}` | $hue |');
    });
  }

  report
    ..writeln()
    ..writeln(perceptualVerdict)
    ..writeln()
    ..writeln('## 4. Cross-mode asymmetry (V6)')
    ..writeln()
    ..writeln(asymmetryNote)
    ..writeln()
    ..writeln('| token / site | light | dark |')
    ..writeln('|---|---|---|');
  for (final row in rows.where((r) => r['code'] == 'V6')) {
    report.writeln(
      '| ${cell(row['expression'])} '
      '| `${cell(row['resolved_value_light'])}` '
      '| `${cell(row['resolved_value_dark'])}` |',
    );
  }

  report
    ..writeln()
    ..writeln('## 5. Role families (V2 / V4 evidence)')
    ..writeln()
    ..writeln('| mode | role | hue spread | has container pair |')
    ..writeln('|---|---|---|---|');
  for (final mode in <String>['light', 'dark']) {
    final block =
        (roles['roles']! as Map<String, Object?>)[mode]!
            as Map<String, Object?>;
    block.forEach((role, v) {
      final entry = v! as Map<String, Object?>;
      final spread = entry['hueSpreadExcludingOnColors'] == null
          ? 'n/a'
          : '${(entry['hueSpreadExcludingOnColors']! as num).toStringAsFixed(1)}°';
      report.writeln(
        '| $mode | $role | $spread | ${entry['hasContainerPair']} |',
      );
    });
  }

  report
    ..writeln()
    ..writeln(roleVerdict)
    ..writeln()
    ..writeln('## 6. `component-map.json` mismatches')
    ..writeln()
    ..writeln(componentMapNote)
    ..writeln()
    ..writeln('## 7. Not verified')
    ..writeln()
    ..writeln(notVerified);

  return report.toString();
}

/// `design_audit/migration_map.md`.
String buildMigrationMarkdown({required Map<String, Object?> violations}) {
  final rows = (violations['violations']! as List<Object?>)
      .cast<Map<String, Object?>>();

  // ---------------------------------------------------------- migration map
  final map = StringBuffer()
    ..writeln('# Colour system migration map')
    ..writeln()
    ..writeln(
      'Generated by `test/design_audit/audit_test.dart`. Findings and '
      'measurements are in `color_system_report.md`.',
    )
    ..writeln()
    ..writeln(migrationPreamble)
    ..writeln()
    ..writeln('## 1. Proposed target token set')
    ..writeln()
    ..writeln(targetTokens)
    ..writeln()
    ..writeln('## 2. Old → new, grouped by target token')
    ..writeln()
    ..writeln('| target token | site | current (light) | current (dark) |')
    ..writeln('|---|---|---|---|');

  final byTarget = <String, List<Map<String, Object?>>>{};
  for (final row in rows) {
    byTarget
        .putIfAbsent(row['proposed_target_token']! as String, () => [])
        .add(row);
  }
  for (final entry in byTarget.entries) {
    for (final row in entry.value) {
      final location = row['line'] == 0
          ? cell(row['file'])
          : '${cell(row['file'])}:${row['line']}';
      map.writeln(
        '| ${cell(entry.key)} | `$location` — ${cell(row['expression'])} '
        '| `${cell(row['resolved_value_light'])}` '
        '| `${cell(row['resolved_value_dark'])}` |',
      );
    }
  }

  map
    ..writeln()
    ..writeln('## 3. Fill order: ColorScheme vs ThemeExtension')
    ..writeln()
    ..writeln(fillOrder)
    ..writeln()
    ..writeln('## 4. Batch plan')
    ..writeln()
    ..writeln(batchPlan);

  return map.toString();
}
