spring.application.name=memox-api
spring.config.import=optional:file:.env.properties[.properties]
spring.flyway.locations=classpath:db/migration
spring.mvc.problemdetails.enabled=true
mybatis.mapper-locations=classpath*:mybatis/**/*_mapper.xml
mybatis.configuration.map-underscore-to-camel-case=true
memox.pagination.default-limit=50
memox.pagination.default-offset=0
