spring.datasource.url=${MEMOX_DB_URL:jdbc:postgresql://localhost:5432/memox}
spring.datasource.username=${MEMOX_DB_USERNAME:giapnt}
spring.datasource.password=${MEMOX_DB_PASSWORD}
spring.datasource.hikari.pool-name=memox-local-pool
