spring.datasource.url=${MEMOX_DB_URL}
spring.datasource.username=${MEMOX_DB_USERNAME}
spring.datasource.password=${MEMOX_DB_PASSWORD}
spring.datasource.hikari.pool-name=memox-production-pool
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.validation-timeout=1000
spring.datasource.hikari.max-lifetime=1800000
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
