import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import type { Page } from '@playwright/test';

/**
 * Step-by-step evidence for the demo flow (M4.12).
 *
 * **A report, not a second set of assertions.** The spec already asserts what
 * each step produced; what M4.12 asks for on top is something a person can read
 * afterwards — the flow, in order, with a picture of the app at each point. A
 * failing step fails the spec; this only records what was on screen when it
 * passed.
 *
 * Artefacts land in `e2e/report/`, which is gitignored: a screenshot committed
 * to the repository is a golden, and goldens live in `test/` where a diff gate
 * watches them. These are evidence for one run, and CI uploads them.
 */
// Resolved from this file, not from the working directory. Playwright is run
// from the repository root in CI and from `e2e/` by hand, and a relative path
// puts the report in a different place each way — which is how a report gets
// written, never found, and assumed not to work.
const reportDir = resolve(__dirname, '..', '..', 'report');

interface Step {
  readonly index: number;
  readonly title: string;
  readonly proves: string;
  readonly shot: string;
}

const steps: Step[] = [];

/**
 * Runs [body] as one numbered step of the flow, then captures the screen.
 *
 * [proves] names the acceptance criterion the step stands for, so the report
 * reads as evidence against M4.12 rather than as a list of taps.
 */
export async function step(
  page: Page,
  title: string,
  proves: string,
  body: () => Promise<void>,
): Promise<void> {
  await body();

  const index = steps.length + 1;
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  // The file name is what the report links to — it sits beside the markdown, so
  // a relative link works wherever the folder is opened. The absolute path is
  // only for writing.
  const shot = `${String(index).padStart(2, '0')}-${slug}.png`;
  const target = join(reportDir, shot);
  mkdirSync(dirname(target), { recursive: true });
  await page.screenshot({ path: target });

  steps.push({ index, title, proves, shot });
}

/**
 * Writes the report once the flow has finished.
 *
 * Markdown rather than HTML: it renders in the CI artefact browser, in an
 * editor, and on GitHub, and it diffs — so two runs can be compared without
 * opening either.
 */
export function writeEvidenceReport(meta: {
  readonly commit: string;
  readonly viewport: string;
}): void {
  const lines = [
    '# Demo flow — step-by-step evidence',
    '',
    'Generated by `e2e/specs/demo-flow.spec.ts`. One row per step of the flow',
    'M4.12 requires, each with the screen as it stood when that step passed.',
    '',
    `| | |`,
    `|---|---|`,
    `| Commit | \`${meta.commit}\` |`,
    `| Viewport | ${meta.viewport} |`,
    `| Steps | ${steps.length} |`,
    '',
    '| # | Step | What it proves | Screen |',
    '|---|---|---|---|',
    ...steps.map(
      (s) =>
        `| ${s.index} | ${s.title} | ${s.proves} | [${s.shot.replace(/\\/g, '/')}](${s.shot.replace(/\\/g, '/')}) |`,
    ),
    '',
    '## What this does not cover',
    '',
    'No review session — that is M5, and there is no session to drive yet. No',
    'visual assertions: the goldens and the strict visual audit own how things',
    'look, and a screenshot comparison here would duplicate them at a much higher',
    'flake rate. These images are evidence of *what happened*, not of *how it',
    'looked*.',
    '',
  ];

  mkdirSync(reportDir, { recursive: true });
  writeFileSync(join(reportDir, 'demo-flow.md'), lines.join('\n'), 'utf8');
}
