import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:memox/core/theme/app_theme.dart';

import '../../support/app_palette.dart';
import '../../support/color_math.dart';

/// Guards the one failure mode that hides until a new screen is built: a
/// `ColorScheme` role nobody declared, generated by `fromSeed` in a hue the app
/// never uses.
///
/// The audit that produced A2 found a **pink** `tertiary`, a neutral-grey
/// `surfaceContainer` ladder on a navy app, and a second red for `error`. None
/// was visible, because the MVP has no Dialog, BottomSheet, NavigationBar, Menu
/// or Chip yet — they would all have surfaced together, on the day someone built
/// Library or Settings.
void main() {
  final schemes = <String, ColorScheme>{
    'light': buildLightTheme().colorScheme,
    'dark': buildDarkTheme().colorScheme,
  };
  final palettes = <String, List<Color>>{
    'light': lightPaletteTokens,
    'dark': darkPaletteTokens,
  };

  test('every role comes from the palette', () {
    for (final entry in schemes.entries) {
      final palette = palettes[entry.key]!;

      _roles(entry.value).forEach((name, color) {
        expect(
          palette,
          contains(color),
          reason:
              '${entry.key}: $name is not an AppColors token — it was left for '
              'fromSeed to invent',
        );
      });
    }
  });

  test('no role strays outside an A2 hue family', () {
    // Independent of the check above rather than implied by it: membership
    // says the value came from the palette, this says the palette itself has
    // not drifted. `fromSeed` generates `tertiaryFixed` at hue 329 — pink — so
    // the band is not hypothetical.
    for (final entry in schemes.entries) {
      _roles(entry.value).forEach((name, color) {
        expect(
          _isInFamily(color),
          isTrue,
          reason: '${entry.key}: $name has hue ${hue(color)} — off palette',
        );
      });
    }
  });
}

/// Every role A2 declares. Each must be a palette token, not a generated one.
Map<String, Color> _roles(ColorScheme s) => <String, Color>{
  'primary': s.primary,
  'onPrimary': s.onPrimary,
  'primaryContainer': s.primaryContainer,
  'onPrimaryContainer': s.onPrimaryContainer,
  'secondary': s.secondary,
  'onSecondary': s.onSecondary,
  'secondaryContainer': s.secondaryContainer,
  'onSecondaryContainer': s.onSecondaryContainer,
  'tertiary': s.tertiary,
  'onTertiary': s.onTertiary,
  'tertiaryContainer': s.tertiaryContainer,
  'onTertiaryContainer': s.onTertiaryContainer,
  'error': s.error,
  'onError': s.onError,
  'errorContainer': s.errorContainer,
  'onErrorContainer': s.onErrorContainer,
  'surface': s.surface,
  'onSurface': s.onSurface,
  'onSurfaceVariant': s.onSurfaceVariant,
  'surfaceDim': s.surfaceDim,
  'surfaceBright': s.surfaceBright,
  'surfaceContainerLowest': s.surfaceContainerLowest,
  'surfaceContainerLow': s.surfaceContainerLow,
  'surfaceContainer': s.surfaceContainer,
  'surfaceContainerHigh': s.surfaceContainerHigh,
  'surfaceContainerHighest': s.surfaceContainerHighest,
  'outline': s.outline,
  'outlineVariant': s.outlineVariant,
  'inverseSurface': s.inverseSurface,
  'onInverseSurface': s.onInverseSurface,
  'inversePrimary': s.inversePrimary,
  'surfaceTint': s.surfaceTint,
  'shadow': s.shadow,
  'scrim': s.scrim,
  // Brightness-independent by definition, so both schemes carry the same
  // light-container values.
  'primaryFixed': s.primaryFixed,
  'primaryFixedDim': s.primaryFixedDim,
  'onPrimaryFixed': s.onPrimaryFixed,
  'onPrimaryFixedVariant': s.onPrimaryFixedVariant,
  'secondaryFixed': s.secondaryFixed,
  'secondaryFixedDim': s.secondaryFixedDim,
  'onSecondaryFixed': s.onSecondaryFixed,
  'onSecondaryFixedVariant': s.onSecondaryFixedVariant,
  'tertiaryFixed': s.tertiaryFixed,
  'tertiaryFixedDim': s.tertiaryFixedDim,
  'onTertiaryFixed': s.onTertiaryFixed,
  'onTertiaryFixedVariant': s.onTertiaryFixedVariant,
};

/// Grey, navy/indigo/steel, or one of the three semantic hues.
bool _isInFamily(Color color) {
  const greyChroma = 0.06;
  if (chroma(color) <= greyChroma) return true;

  final h = hue(color);
  if (h == null) return true;

  const families = <(double, double)>[
    (195, 255), // navy, indigo, steel — the brand and every surface
    (340, 360), // danger
    (145, 175), // success
    (25, 55), // warning
  ];

  return families.any((band) => h >= band.$1 && h <= band.$2);
}
