import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:memox/core/theme/app_theme.dart';

import '../../support/app_palette.dart';
import '../../support/color_math.dart';

/// 26 standard roles and 19 add-ons — the set Material 3 currently defines,
/// with the three deprecated roles and `surfaceTint` outside it.
const int _materialColorRoleCount = 45;

/// Guards the one failure mode that hides until a new screen is built: a
/// `ColorScheme` role nobody declared, generated by `fromSeed` in a hue the app
/// never uses.
///
/// The audit that produced A2 found a **pink** `tertiary`, a neutral-grey
/// `surfaceContainer` ladder on a navy app, and a second red for `error`. None
/// was visible, because the MVP has no Dialog, BottomSheet, NavigationBar, Menu
/// or Chip yet — they would all have surfaced together, on the day someone built
/// Library or Settings.
void main() {
  final schemes = <String, ColorScheme>{
    'light': buildLightTheme().colorScheme,
    'dark': buildDarkTheme().colorScheme,
    // High contrast re-points three border tokens and nothing else, so it is
    // held to the same two rules rather than exempted from them: a stronger
    // edge still has to be a colour from this palette, in a hue this palette
    // uses. It is a legibility setting, not a licence for a second system.
    'high contrast light': buildHighContrastLightTheme().colorScheme,
    'high contrast dark': buildHighContrastDarkTheme().colorScheme,
  };
  final palettes = <String, List<Color>>{
    'light': lightPaletteTokens,
    'dark': darkPaletteTokens,
    'high contrast light': lightPaletteTokens,
    'high contrast dark': darkPaletteTokens,
  };

  test('every role comes from the palette', () {
    for (final entry in schemes.entries) {
      final palette = palettes[entry.key]!;

      _roles(entry.value).forEach((name, color) {
        expect(
          palette,
          contains(color),
          reason:
              '${entry.key}: $name is not an AppColors token — it was left for '
              'fromSeed to invent',
        );
      });
    }
  });

  test('fixed roles are identical in light and dark', () {
    // The one property the two tests above structurally cannot see. Both ask
    // whether a role's value is *ours*; neither compares the two schemes to
    // each other, so twelve roles disagreed across brightness for as long as
    // they were undeclared and every gate stayed green.
    final light = schemes['light']!;
    final dark = schemes['dark']!;

    final fixed = <String, (Color, Color)>{
      'primaryFixed': (light.primaryFixed, dark.primaryFixed),
      'primaryFixedDim': (light.primaryFixedDim, dark.primaryFixedDim),
      'onPrimaryFixed': (light.onPrimaryFixed, dark.onPrimaryFixed),
      'onPrimaryFixedVariant': (
        light.onPrimaryFixedVariant,
        dark.onPrimaryFixedVariant,
      ),
      'secondaryFixed': (light.secondaryFixed, dark.secondaryFixed),
      'secondaryFixedDim': (light.secondaryFixedDim, dark.secondaryFixedDim),
      'onSecondaryFixed': (light.onSecondaryFixed, dark.onSecondaryFixed),
      'onSecondaryFixedVariant': (
        light.onSecondaryFixedVariant,
        dark.onSecondaryFixedVariant,
      ),
      'tertiaryFixed': (light.tertiaryFixed, dark.tertiaryFixed),
      'tertiaryFixedDim': (light.tertiaryFixedDim, dark.tertiaryFixedDim),
      'onTertiaryFixed': (light.onTertiaryFixed, dark.onTertiaryFixed),
      'onTertiaryFixedVariant': (
        light.onTertiaryFixedVariant,
        dark.onTertiaryFixedVariant,
      ),
    };

    fixed.forEach((name, pair) {
      expect(
        pair.$1,
        pair.$2,
        reason:
            '$name differs between light and dark — a `*Fixed` role is one '
            'colour for both themes, so it must be one constant',
      );
    });
  });

  test('declares exactly the 45 Material 3 roles', () {
    // The inventory below is written by hand, so this is the one line that
    // notices when a role is added to it or dropped from it. 46 was the count
    // for a while — the 45 plus `surfaceTint`, which is not a role (M100.17).
    expect(_roles(schemes['light']!).length, _materialColorRoleCount);
  });

  test('surfaceTint is the SDK default, primary', () {
    // Not passed to the constructor on purpose: it is a mechanism, not a
    // role, and every themed component suppresses it with
    // `surfaceTintColor: transparent` anyway. What it resolves to is
    // therefore the SDK's own `_surfaceTint ?? primary`, pinned here so a
    // Flutter that changes that default is noticed on this line rather than
    // on an untended elevated widget.
    for (final entry in schemes.entries) {
      expect(
        entry.value.surfaceTint,
        entry.value.primary,
        reason: '${entry.key}: surfaceTint is no longer the SDK default',
      );
    }
  });

  test('the three deprecated roles carry no value of their own', () {
    // `background`, `onBackground` and `surfaceVariant` are not among the 45
    // and nothing in the app reads them. The constructor still accepts them,
    // so the only way to prove nobody passed one is to read the getter and
    // see the SDK's fallback come back — which is the one thing a deprecated
    // getter is still good for, hence the ignores.
    for (final entry in schemes.entries) {
      final scheme = entry.value;
      final fallbacks = <String, (Color, Color)>{
        // ignore: deprecated_member_use
        'background': (scheme.background, scheme.surface),
        // ignore: deprecated_member_use
        'onBackground': (scheme.onBackground, scheme.onSurface),
        // ignore: deprecated_member_use
        'surfaceVariant': (scheme.surfaceVariant, scheme.surface),
      };

      fallbacks.forEach((name, pair) {
        expect(
          pair.$1,
          pair.$2,
          reason:
              '${entry.key}: deprecated `$name` was passed a value of its own',
        );
      });
    }
  });

  test('no role strays outside an A2 hue family', () {
    // Independent of the check above rather than implied by it: membership
    // says the value came from the palette, this says the palette itself has
    // not drifted. `fromSeed` generates `tertiaryFixed` at hue 329 — pink — so
    // the band is not hypothetical.
    for (final entry in schemes.entries) {
      _roles(entry.value).forEach((name, color) {
        expect(
          _isInFamily(color),
          isTrue,
          reason: '${entry.key}: $name has hue ${hue(color)} — off palette',
        );
      });
    }
  });
}

/// The 45 Material 3 colour roles, every one of which A2 declares. Each must
/// be a palette token, not a generated one.
///
/// `surfaceTint` is deliberately not here: it is a Flutter mechanism rather
/// than a role, the scheme does not pass it, and `surfaceTint is the SDK
/// default` above is what pins the value it resolves to.
Map<String, Color> _roles(ColorScheme s) => <String, Color>{
  'primary': s.primary,
  'onPrimary': s.onPrimary,
  'primaryContainer': s.primaryContainer,
  'onPrimaryContainer': s.onPrimaryContainer,
  'secondary': s.secondary,
  'onSecondary': s.onSecondary,
  'secondaryContainer': s.secondaryContainer,
  'onSecondaryContainer': s.onSecondaryContainer,
  'tertiary': s.tertiary,
  'onTertiary': s.onTertiary,
  'tertiaryContainer': s.tertiaryContainer,
  'onTertiaryContainer': s.onTertiaryContainer,
  'error': s.error,
  'onError': s.onError,
  'errorContainer': s.errorContainer,
  'onErrorContainer': s.onErrorContainer,
  'surface': s.surface,
  'onSurface': s.onSurface,
  'onSurfaceVariant': s.onSurfaceVariant,
  'surfaceDim': s.surfaceDim,
  'surfaceBright': s.surfaceBright,
  'surfaceContainerLowest': s.surfaceContainerLowest,
  'surfaceContainerLow': s.surfaceContainerLow,
  'surfaceContainer': s.surfaceContainer,
  'surfaceContainerHigh': s.surfaceContainerHigh,
  'surfaceContainerHighest': s.surfaceContainerHighest,
  'outline': s.outline,
  'outlineVariant': s.outlineVariant,
  'inverseSurface': s.inverseSurface,
  'onInverseSurface': s.onInverseSurface,
  'inversePrimary': s.inversePrimary,
  'shadow': s.shadow,
  'scrim': s.scrim,
  // Brightness-independent by definition — and that is now true rather than
  // assumed. Until M99.47 these twelve were the only roles left undeclared,
  // so each resolved through `ColorScheme`'s own fallback to its *base* role
  // (`_primaryFixed ?? primary`): a fill-level tone where the spec asks for a
  // container-level one, and a different value in each brightness. The comment
  // that stood here claimed the opposite, and the two assertions in this file
  // could not catch it — `primaryLight` and `primaryDark` are both palette
  // tokens in the right hue family, so both passed while disagreeing.
  // `fixed roles are identical in light and dark` below is what closes that.
  'primaryFixed': s.primaryFixed,
  'primaryFixedDim': s.primaryFixedDim,
  'onPrimaryFixed': s.onPrimaryFixed,
  'onPrimaryFixedVariant': s.onPrimaryFixedVariant,
  'secondaryFixed': s.secondaryFixed,
  'secondaryFixedDim': s.secondaryFixedDim,
  'onSecondaryFixed': s.onSecondaryFixed,
  'onSecondaryFixedVariant': s.onSecondaryFixedVariant,
  'tertiaryFixed': s.tertiaryFixed,
  'tertiaryFixedDim': s.tertiaryFixedDim,
  'onTertiaryFixed': s.onTertiaryFixed,
  'onTertiaryFixedVariant': s.onTertiaryFixedVariant,
};

/// Grey, navy/indigo/steel, or one of the three semantic hues.
bool _isInFamily(Color color) {
  const greyChroma = 0.06;
  if (chroma(color) <= greyChroma) return true;

  final h = hue(color);
  if (h == null) return true;

  const families = <(double, double)>[
    (195, 255), // navy, indigo, steel — the brand and every surface
    (340, 360), // danger
    (145, 175), // success
    (25, 55), // warning
  ];

  return families.any((band) => h >= band.$1 && h <= band.$2);
}
