import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:memox/core/theme/app_theme.dart';

import '../../support/app_palette.dart';
import '../../support/color_math.dart';

/// Guards the one failure mode that hides until a new screen is built: a
/// `ColorScheme` role nobody declared, generated by `fromSeed` in a hue the app
/// never uses.
///
/// The audit that produced A2 found a **pink** `tertiary`, a neutral-grey
/// `surfaceContainer` ladder on a navy app, and a second red for `error`. None
/// was visible, because the MVP has no Dialog, BottomSheet, NavigationBar, Menu
/// or Chip yet — they would all have surfaced together, on the day someone built
/// Library or Settings.
void main() {
  final schemes = <String, ColorScheme>{
    'light': buildLightTheme().colorScheme,
    'dark': buildDarkTheme().colorScheme,
  };
  final palettes = <String, List<Color>>{
    'light': lightPaletteTokens,
    'dark': darkPaletteTokens,
  };

  test('every role comes from the palette', () {
    for (final entry in schemes.entries) {
      final palette = palettes[entry.key]!;

      _roles(entry.value).forEach((name, color) {
        expect(
          palette,
          contains(color),
          reason:
              '${entry.key}: $name is not an AppColors token — it was left for '
              'fromSeed to invent',
        );
      });
    }
  });

  test('fixed roles are identical in light and dark', () {
    // The one property the two tests above structurally cannot see. Both ask
    // whether a role's value is *ours*; neither compares the two schemes to
    // each other, so twelve roles disagreed across brightness for as long as
    // they were undeclared and every gate stayed green.
    final light = schemes['light']!;
    final dark = schemes['dark']!;

    final fixed = <String, (Color, Color)>{
      'primaryFixed': (light.primaryFixed, dark.primaryFixed),
      'primaryFixedDim': (light.primaryFixedDim, dark.primaryFixedDim),
      'onPrimaryFixed': (light.onPrimaryFixed, dark.onPrimaryFixed),
      'onPrimaryFixedVariant': (
        light.onPrimaryFixedVariant,
        dark.onPrimaryFixedVariant,
      ),
      'secondaryFixed': (light.secondaryFixed, dark.secondaryFixed),
      'secondaryFixedDim': (light.secondaryFixedDim, dark.secondaryFixedDim),
      'onSecondaryFixed': (light.onSecondaryFixed, dark.onSecondaryFixed),
      'onSecondaryFixedVariant': (
        light.onSecondaryFixedVariant,
        dark.onSecondaryFixedVariant,
      ),
      'tertiaryFixed': (light.tertiaryFixed, dark.tertiaryFixed),
      'tertiaryFixedDim': (light.tertiaryFixedDim, dark.tertiaryFixedDim),
      'onTertiaryFixed': (light.onTertiaryFixed, dark.onTertiaryFixed),
      'onTertiaryFixedVariant': (
        light.onTertiaryFixedVariant,
        dark.onTertiaryFixedVariant,
      ),
    };

    fixed.forEach((name, pair) {
      expect(
        pair.$1,
        pair.$2,
        reason:
            '$name differs between light and dark — a `*Fixed` role is one '
            'colour for both themes, so it must be one constant',
      );
    });
  });

  test('no role strays outside an A2 hue family', () {
    // Independent of the check above rather than implied by it: membership
    // says the value came from the palette, this says the palette itself has
    // not drifted. `fromSeed` generates `tertiaryFixed` at hue 329 — pink — so
    // the band is not hypothetical.
    for (final entry in schemes.entries) {
      _roles(entry.value).forEach((name, color) {
        expect(
          _isInFamily(color),
          isTrue,
          reason: '${entry.key}: $name has hue ${hue(color)} — off palette',
        );
      });
    }
  });
}

/// Every role A2 declares. Each must be a palette token, not a generated one.
Map<String, Color> _roles(ColorScheme s) => <String, Color>{
  'primary': s.primary,
  'onPrimary': s.onPrimary,
  'primaryContainer': s.primaryContainer,
  'onPrimaryContainer': s.onPrimaryContainer,
  'secondary': s.secondary,
  'onSecondary': s.onSecondary,
  'secondaryContainer': s.secondaryContainer,
  'onSecondaryContainer': s.onSecondaryContainer,
  'tertiary': s.tertiary,
  'onTertiary': s.onTertiary,
  'tertiaryContainer': s.tertiaryContainer,
  'onTertiaryContainer': s.onTertiaryContainer,
  'error': s.error,
  'onError': s.onError,
  'errorContainer': s.errorContainer,
  'onErrorContainer': s.onErrorContainer,
  'surface': s.surface,
  'onSurface': s.onSurface,
  'onSurfaceVariant': s.onSurfaceVariant,
  'surfaceDim': s.surfaceDim,
  'surfaceBright': s.surfaceBright,
  'surfaceContainerLowest': s.surfaceContainerLowest,
  'surfaceContainerLow': s.surfaceContainerLow,
  'surfaceContainer': s.surfaceContainer,
  'surfaceContainerHigh': s.surfaceContainerHigh,
  'surfaceContainerHighest': s.surfaceContainerHighest,
  'outline': s.outline,
  'outlineVariant': s.outlineVariant,
  'inverseSurface': s.inverseSurface,
  'onInverseSurface': s.onInverseSurface,
  'inversePrimary': s.inversePrimary,
  'surfaceTint': s.surfaceTint,
  'shadow': s.shadow,
  'scrim': s.scrim,
  // Brightness-independent by definition — and that is now true rather than
  // assumed. Until M99.47 these twelve were the only roles left undeclared,
  // so each resolved through `ColorScheme`'s own fallback to its *base* role
  // (`_primaryFixed ?? primary`): a fill-level tone where the spec asks for a
  // container-level one, and a different value in each brightness. The comment
  // that stood here claimed the opposite, and the two assertions in this file
  // could not catch it — `primaryLight` and `primaryDark` are both palette
  // tokens in the right hue family, so both passed while disagreeing.
  // `fixed roles are identical in light and dark` below is what closes that.
  'primaryFixed': s.primaryFixed,
  'primaryFixedDim': s.primaryFixedDim,
  'onPrimaryFixed': s.onPrimaryFixed,
  'onPrimaryFixedVariant': s.onPrimaryFixedVariant,
  'secondaryFixed': s.secondaryFixed,
  'secondaryFixedDim': s.secondaryFixedDim,
  'onSecondaryFixed': s.onSecondaryFixed,
  'onSecondaryFixedVariant': s.onSecondaryFixedVariant,
  'tertiaryFixed': s.tertiaryFixed,
  'tertiaryFixedDim': s.tertiaryFixedDim,
  'onTertiaryFixed': s.onTertiaryFixed,
  'onTertiaryFixedVariant': s.onTertiaryFixedVariant,
};

/// Grey, navy/indigo/steel, or one of the three semantic hues.
bool _isInFamily(Color color) {
  const greyChroma = 0.06;
  if (chroma(color) <= greyChroma) return true;

  final h = hue(color);
  if (h == null) return true;

  const families = <(double, double)>[
    (195, 255), // navy, indigo, steel — the brand and every surface
    (340, 360), // danger
    (145, 175), // success
    (25, 55), // warning
  ];

  return families.any((band) => h >= band.$1 && h <= band.$2);
}
